keep-open=yes

# Качество видео для веба
ytdl-format=bestvideo[height<=?1080][fps<=?144]+bestaudio/best

# Использовать RAM-кеш (даже для локального ввода)
cache=yes
# cache-on-disk=no # кеш на диске, вместо RAM
# Дополнительный размер кеша
demuxer-max-bytes=500M
demuxer-max-back-bytes=100M

# Масштабирование
# scale=ewa_lanczossharp
# dscale=mitchell
# cscale=spline36

# Плавность и синхронизация
# video-sync=display-resample
# interpolation=yes
# tscale=oversample

# HDR и управление цветом
# target-colorspace-hint=yes
# hdr-compute-peak=yes

# Высокое качество видеовыхода (OpenGL)
# vo=gpu
# hwdec=auto-safe # Автоматическое аппаратное ускорение
# profile=gpu-hq # Загрузка профиля высокого качества

# Аппаратное ускорение для уменьшения нагрузки на CP
hwdec=auto

# Интерфейс
osd-font-size=24
